added pyp file

diff --git a/tests/py_custom_install b/tests/py_custom_install
--- a/tests/py_custom_install
+++ b/tests/py_custom_install
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+# Joan Grau
+#
+# Make sure to have alias set to:
+# alias pyp='py_custom_install $(pwd) && if [ $(echo $?) -ne 0 ]; then source $(pwd)/env/bin/activate; fi'
+
 #ENV
 req=requirements.txt
 echo "Using directory $1"
@@ -10,11 +15,45 @@ create_env()
 	if [ -f $req ]; then
 		source ./env/bin/activate
 		pip install -r $req
+	else
+		install_from_file
 	fi
 
 }
 
+install_from_file()
+{
 
-create_env
 
-alias='py_custom_install $(pwd) && source $(pwd)/env/bin/activate'
+while read i; do
+        if [[ $i == *"from"* ]]; then
+                case $(echo $i | cut -d' ' -f 2) in
+                        "google.cloud")
+                                pip install $(echo "google-cloud-$(echo $i | cut -d' ' -f 4 | tr _ -)")
+                                ;;
+                        *)
+                                pip install $(echo $i | cut -d' ' -f 2)
+                                ;;
+                esac
+        else
+                pip install $(echo $i | cut -d' ' -f 2)
+        fi
+
+done <<< $(cat main.py | grep 'import')
+
+}
+
+
+main()
+{
+	if [[ -n $(echo *.py) ]]; then
+		echo -e "\nERROR: Check if you are in the correct directory"
+		echo    "       (no existing .py files found)"
+		echo -e "\nExiting...\n"
+	else
+		create_env
+	fi
+}
+
+main
+
